name: Run Python Bot
env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

on:
  workflow_dispatch:   # Manual trigger
  schedule:
    - cron: "0 * * * *"  # Hourly run
  push:
    branches: [ main ]   # On push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run bot
        run: python main.py

